services:
  php_laravel:
    container_name: php_laravel
    build:
      context: ./docker/php
      dockerfile: Dockerfile      
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./projects:/var/www
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    working_dir: /var/www
    ports:
      - "9003:9003" # Porta padrão do Xdebug
      - "9000:9000" # Porta para o servidor Laravel   
    networks:
      - laravel-network
    depends_on:
      - mysql_laravel
      - redis_laravel
      - node_laravel

  nginx_laravel:
    container_name: nginx_laravel
    image: nginx:latest
    ports:
      - "443:443"
      - "8788:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./projects:/var/www
    depends_on:
      - php_laravel
    networks:
      - laravel-network

  mysql_laravel:
    container_name: mysql_laravel
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile      
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-network

  redis_laravel:
    container_name: redis_laravel
    build:
      context: ./docker/redis
      dockerfile: Dockerfile      
    networks:
      - laravel-network

  node_laravel:
    container_name: node_laravel
    build:
      context: ./docker/node
      dockerfile: Dockerfile      
    volumes:
      - ./projects:/var/www  # Monta toda a pasta projects dentro do container
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql-data: